apiVersion: v1
kind: Service
metadata:
  name: etcd-001
  namespace: rejoinable-etcd
  labels:
    app: etcd

spec:
  type: LoadBalancer
  ports:
  - name: etcd-db
    port: 2379
    targetPort: 2379
    nodePort: 32001
  - name: etcd-cluster
    port: 2380
    targetPort: 2380
  selector:
    app: etcd
    node-id: etcd-001
