apiVersion: v1
kind: Service
metadata:
  name: etcd-002
  namespace: rejoinable-etcd
  labels:
    app: etcd

spec:
  type: LoadBalancer
  ports:
  - name: etcd-db
    port: 2379
    targetPort: 2379
    nodePort: 32002
  - name: etcd-cluster
    port: 2380
    targetPort: 2380
  selector:
    app: etcd
    node-id: etcd-002
