apiVersion: v1
kind: Service
metadata:
  name: etcd-lb
  namespace: rejoinable-etcd
  labels:
    app: etcd

spec:
  ports:
  - name: etcd-db
    port: 2379
    targetPort: 2379
  selector:
    app: etcd