apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-001
  namespace: rejoinable-etcd
  labels:
    app: etcd
    node-id: etcd-001

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: etcd
        node-id: etcd-001
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2379"
        prometheus.io/path: "/metrics"

    spec:
      volumes:
      - name: etcd-data-dir
        emptyDir: {}

      containers:
      - name: etcd
        image: oberthur/docker-rejoinable-etcd:2.3.7
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_NAME
          value: "etcd1"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd-001.rejoinable-etcd:2379"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://etcd-001.rejoinable-etcd:2380"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: "etcd-cluster-1"
        - name: ETCD_INITIAL_CLUSTER
          value: "etcd1=http://etcd-001.rejoinable-etcd:2380,etcd2=http://etcd-002.rejoinable-etcd:2380,etcd3=http://etcd-003.rejoinable-etcd:2380"
        - name: ETCD_OTHER_PEERS_CLIENT_URLS
          value: "http://etcd-002.rejoinable-etcd:2379,http://etcd-003.rejoinable-etcd:2379"
        - name: ETCD_DEBUG
          value: "true"

        volumeMounts:
          - mountPath: /etcd1.etcd
            name: etcd-data-dir

        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi

        ports:
        - name: etcd-db
          containerPort: 2379
          protocol: TCP
        - name: etcd-cluster
          containerPort: 2380
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 15
          timeoutSeconds: 5